### Get all tasks
GET http://localhost:8000/api/v2/tasks
Content-Type: application/json
Authorization: Bearer 1|XJhAXxt29HoPOUhCvmh9rE0V8UA09DjGuasngPLW8bc125c0

### Get one task
GET http://localhost:8000/api/v2/tasks/11
Content-Type: application/json
Authorization: Bearer 1|XJhAXxt29HoPOUhCvmh9rE0V8UA09DjGuasngPLW8bc125c0

### Create a new task
POST http://localhost:8000/api/v2/tasks
Content-Type: application/json
Authorization: Bearer 6|PbhVD3fPzH3fUWOK6fiymMwGqRoe2HoEFNFdl9rE289947ca

{
    "name": "Buy milk"
}

### Update a task
PUT http://localhost:8000/api/v2/tasks/21
Content-Type: application/json
Authorization: Bearer 1|XJhAXxt29HoPOUhCvmh9rE0V8UA09DjGuasngPLW8bc125c0

{
    "name": "Task one"
}

### Mark a task as complete
PATCH http://localhost:8000/api/v2/tasks/1/complete
Content-Type: application/json
Authorization: Bearer 1|XJhAXxt29HoPOUhCvmh9rE0V8UA09DjGuasngPLW8bc125c0

{
    "is_completed": true
}

### Delete a task
DELETE http://localhost:8000/api/v2/tasks/11
Authorization: Bearer 1|XJhAXxt29HoPOUhCvmh9rE0V8UA09DjGuasngPLW8bc125c0

### Get all summaries
GET http://localhost:8003/api/v2/summaries
Content-Type: application/json
Authorization: Bearer 1|0Ue62SecA7R5DmM9M8FoRpo7rMbQAeMC0vzkzMAX2e562ae3
